### ISSUE TITLE
ISE: Connection is still allocated

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#44]
Apparently, using ``BasicHttpClientConnectionManager`` (e.g. inside ``UnixHttpClient``) is not ok since it provides a single connection.

This throws the exception:

```java
final Docker docker = new LocalDocker(
    new File("/var/run/docker.sock")
);
docker.ping();
docker.ping();
```

Becuase the connection is still allocated from the first call. We should either close the connection after each call somehow (not always wanted, of course), or maybe use [PoolingClientConnectionManager](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingClientConnectionManager.html)?

**Comment by amihaiemil** [comment]
@llorllale Do you know Apache HttpClient? Want to fix this one?

**Comment by llorllale** [comment]
@amihaiemil yes, I've used this lib before. This is one of those surprises (there will be more).

Question: do we need this method at all?

```java
    /**
     * Ping the Docker Engine.
     * @return True if it responds with 200 OK, false otherwise.
     * @throws IOException If there's network problem.
     */
    boolean ping() throws IOException;
```

**Comment by llorllale** [comment]
@amihaiemil anyway, I can work on this

**Comment by amihaiemil** [comment]
@llorllale Yes, we need that method. That's the first thing a user does when using an API, right? Try to ping it :D 

And the issue is with other methods as well, anyway. I would look into that Pooling connection manager, I think that's the way to go.

**Comment by amihaiemil** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/amihaiemil/docker-java-api/issues/44#issuecomment-373027671))

@amihaiemil Job [#44](https://github.com/amihaiemil/docker-java-api/issues/44) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/amihaiemil/docker-java-api/issues/44#issuecomment-373027671))

@amihaiemil Job [#44](https://github.com/amihaiemil/docker-java-api/issues/44) is already in scope

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#44](https://github.com/amihaiemil/docker-java-api/issues/44) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/731605028). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@llorllale This would be a reasearch task, I guess (not sure how much you can figure out in 30min). Of course, it's ok to leave a puzzle with your findings.

**Comment by llorllale** [comment]
@amihaiemil will this work for you?

```java
    @Override
    public final boolean ping() throws IOException {
        final HttpGet get = new HttpGet(this.baseUri.toString() + "/_ping");
        final HttpResponse response = this.client.execute(get);
        get.releaseConnection();
        return response.getStatusLine().getStatusCode() == HttpStatus.SC_OK;
    }
```

**Comment by amihaiemil** [comment]
@llorllale We should also do that, close the connection wherever possible, but it is not enough. The issue is the way the HttpClient is built: Basic connection manager is used, which has a single connection.

We need Pooling connection manager because we won't be able to close all the connections right away. For instance, ``Container.followLogs()`` will return an InputStream which will have to be consumed by the user directly, we won't be able to close the connection right before returning the InputStream since then they wouldn't be able to read from it anymore. 

As you see, a single HttpClient instance is passed around the library, so if we only rely on closing connections manually, the following snippet won't work:

```java
    final Container container = docker.containers.get(...);
    final InputStream logsStream = container.followLogs(); //here we did not close it
    docker.ping();//fail here, connection is still assigned.
```

**Comment by llorllale** [comment]
@amihaiemil I think you've done the research already.

I'm think this connection pooling should be done both for unix and non-unix/remote endpoints. So we should probably extract that (huge!) block of code that creates the client connection manager in `UnixHttpClient` into its own class. That class needs to be somehow fed the `maxConnections` configuration somehow.

**Comment by amihaiemil** [comment]
@llorllale yes, we could do that, but not yet. The building of the remote HttpClient will be even funnier: you have to register https protocol, with SSL socket factory (something like that), in order to use the supplied certificates and encrypt the request properly.
 
So, for now, let's not extract anything, just make them work separately and refactor later.
Try to use Pooling cm for the UnixHttpClient, see how it works -- I'm also not sure how to use that properly yet :D it shouldn't be hard, though, I think you just pass it the maxConnections number somehow.

**Comment by llorllale** [comment]
@amihaiemil sorry for requesting confirmation so much

WDYT of this? Notice the new ctor that accepts `Supplier<HttpClient>`. It is there solely to leave the ctor chain starting at `UnixHttpClient(final File sockerFile)` intact.

```java
    /**
     * Ctor.
     * @param socketFile Unix socket on disk.
     */
    UnixHttpClient(final File socketFile) {
        this(() -> {
            final PoolingHttpClientConnectionManager pool = new PoolingHttpClientConnectionManager(
                RegistryBuilder
                    .<ConnectionSocketFactory>create()
                    .register(
                        "unix",
                        new ConnectionSocketFactory() {
                            @Override
                            public Socket createSocket(
                                final HttpContext httpContext
                            ) throws IOException {
                                return UnixSocketChannel.open().socket();
                            }

                            @Override
                            public Socket connectSocket(
                                final int connectionTimeout,
                                final Socket socket,
                                final HttpHost host,
                                final InetSocketAddress remoteAddress,
                                final InetSocketAddress localAddress,
                                final HttpContext context
                            ) throws IOException {
                                socket.setSoTimeout(connectionTimeout);
                                socket.getChannel().connect(
                                    new UnixSocketAddress(socketFile)
                                );
                                return socket;
                            }
                        })
                    .build()
            );
            pool.setDefaultMaxPerRoute(0);
            pool.setMaxTotal(0);
            return HttpClientBuilder.create()
                .setConnectionManager(pool)
                .build();
        });
    }

    /**
     * Ctor.
     * @param client The HttpClient.
     */
    UnixHttpClient(Supplier<HttpClient> client) {
      this(client.get());
    }

    /**
     * Ctor.
     * @param client Decorated HttpClient.
     */
    UnixHttpClient(final HttpClient client) {
        this.client = client;
    }

```

**Comment by amihaiemil** [comment]
@llorllale 

>sorry for requesting confirmation so much

Not a problem. Although you can also make fast PRs and we can discuss there :-? same for me. 

Yes, looks nice, given that you have to call those setters on the Pooling cm. Are you sure it cannot accept them through its ctor?

**Comment by llorllale** [comment]
@amihaiemil [yes, I'm sure](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html)

**Comment by amihaiemil** [comment]
@llorllale I see, ok

**Comment by llorllale** [comment]
@amihaiemil do we agree that adding a test for this requires completing that other task about implementing a socket server?

**Comment by amihaiemil** [comment]
@llorllale yes, I think we may need that. But for now, you can simply add a second ``docker.ping()`` to that IT case... then, we also need to setup Travis or Rultor somehow to run the IT cases as well, that's not yet done :D

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#51](https://github.com/amihaiemil/docker-java-api/issues/51), [#52](https://github.com/amihaiemil/docker-java-api/issues/52) are still not solved.

**Comment by llorllale** [comment]
@amihaiemil can we close this?
* This was solved in PR #50 which got merged
* Puzzle #51 for completing one test left due to impediment on #41
* Puzzle #52 left for making the connection pool size configurable

**Comment by amihaiemil** [comment]
@llorllale sure, thanks

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#44](https://github.com/amihaiemil/docker-java-api/issues/44) is now out of scope

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#51](https://github.com/amihaiemil/docker-java-api/issues/51) is still not solved; solved: [#52](https://github.com/amihaiemil/docker-java-api/issues/52).
